# Generated by Django 5.0.6 on 2024-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.CharField(max_length=512)),
                ('shorten_url', models.CharField(max_length=5)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
