# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_shortener',
            name='shorten_url',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
